#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

$autoloadPath = __DIR__.'/vendor/autoload.php';
if (!file_exists($autoloadPath)) {
    fwrite(STDERR, " Error: Falta el autoloader de Composer. Ejecuta 'composer install' primero.\n");
    exit(1);
}

require $autoloadPath;

try {
    /** @var Application $app */
    $app = require_once __DIR__.'/bootstrap/app.php';

    $status = $app->handleCommand(new ArgvInput);
    exit($status);
} catch (Throwable $e) {
    fwrite(STDERR, " Error: {$e->getMessage()}\n");
    fwrite(STDERR, $e->getTraceAsString() . "\n");
    exit(1);
}

